
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Classique.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Abonné
{

    public Abonné()
    {

        this.Achat = new HashSet<Achat>();

    }


    public int Code_Abonné { get; set; }

    public string Nom_Abonné { get; set; }

    public string Prénom_Abonné { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string Adresse { get; set; }

    public string Ville { get; set; }

    public string Code_Postal { get; set; }

    public Nullable<int> Code_Pays { get; set; }

    public string Email { get; set; }

    public string UserId { get; set; }

    public Nullable<int> Credit { get; set; }



    public virtual Pays Pays { get; set; }

    public virtual ICollection<Achat> Achat { get; set; }

}

}
