
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Classique.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Achat
{

    public int Code_Achat { get; set; }

    public int Code_Enregistrement { get; set; }

    public int Code_Abonné { get; set; }



    public virtual Abonné Abonné { get; set; }

    public virtual Enregistrement Enregistrement { get; set; }

}

}
